### ISSUE TITLE
Design Offseting Certificat

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/Design_-_Contents#4]
**Description**
---
We need to define the Design of the Offsetting Carbonable Certificate. 

The criteria of the Offsetting Carbonable Certificate :
- One Project per Certificate 
- Aggregate Offsetting (number of Carbon Credit) for the same Project, when user asking to Offset.

Data example: <https://registry.goldstandard.org/credit-blocks/details/350890>

Style / Format inspiration : <https://www.google.com/search?rlz=1C1CHBD_enFR1012FR1012&q=Carbon+offsetting+certificate&tbm=isch&sa=X&ved=2ahUKEwj5vYa7ktr_AhXqVaQEHb8HBw8Q0pQJegQIChAB&biw=1918&bih=1479>

The data to put in the certificate :

**Data**
---

*Title*
• Certificate of Carbon Contributions Retirement

*Overall* 
• Number of Contributions
• Carbonable Retirement date 

*Project Data*
•  Project name :
•  Project developer :
•  Standard :
•  Country :
•  GPS location:
•  Project category : ARR ou REDD+ 
•  Project type  : (Forest, mangrove, etc...)

*Carbon Credit Data:* 
• Serial number
• Issuance number (range)
• Issuance date
• Standard Status: (VCS ou ARU ou...)
• Monitoring period (date range)
• Vintage
(• Credit Status (Retired))

(*History*
• Change in statuses + Timestamp
• Ownership changes + Timestamp)

*Img Project*
• _Logo Standard_
• Image Projet
• Logo Carbonable 

HAS TO / MVP

*Title*
• Certificate of Carbon Contributions Retirement

*Overall* 
• Number of Contributions
• Carbonable Retirement date 

*Project Data*
•  Project name :
•  Project developer :
•  Standard :
•  Country :
•  GPS location:
•  Project category : ARR ou REDD+ 
•  Project type  : (Forest, mangrove, etc...)

*Carbon Credit Data:* 
• Serial number
• Vintage

*Img Project*
• Image Projet
• Logo Carbonable 

The ERC used to for the certificate will be an ERC-721.

**Acceptance Criteria**
---
- [ ] The UI of the Carbonable certificate need to be done on Figma

### **RESULTS**
--- 
Approved Design (the one below with the number of tones highlighted):
https://www.figma.com/file/TxyvqO53GlCiTaJOE26AwM/dApp?type=design&node-id=2925%3A179045&mode=design&t=gcnCuvcoV3AUPBQK-1
* One is the actual pdf versin
* One is the digital version

**Comment by G2CARBZ** [comment]
Design approved (the one below with the # of tonnes highlighted): 
https://www.figma.com/file/TxyvqO53GlCiTaJOE26AwM/dApp?type=design&node-id=2925%3A179045&mode=design&t=gcnCuvcoV3AUPBQK-1

**Comment by G2CARBZ** [comment]
Design approved (the one below the number of tonnes highlighted):
https://www.figma.com/file/TxyvqO53GlCiTaJOE26AwM/dApp?type=design&node-id=2925%3A179045&mode=design&t=gcnCuvcoV3AUPBQK-1
